### ISSUE TITLE
the code is too messy

### ISSUE THREAD

**Issue by PoIygon** [Sprout-Inc/sprout-website#9]
theres navbar code in a <style> tag even though it could be placed in a seperate css file, you copied the css file because nobody would style a video player, the code too long

short code:
```html
<p>hi there buckeroo</p>
```

your code:
```html
<p>
hi there buckeroo
</p>
```

also you copied the navbar css from w3 schools and your code is tabbed 2 times, not 4 times.

**Comment by AIGamesDeveloper** [comment]
The website has shut down. No mistakes will be made again. Deleting this topic
